### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zjh299** [Li-Qingyun/RSCoTr#11]
python tools/train.py configs/multi/MTL_swin-t-p4-w7_1x1_dior.py --load-task-pretrain --work-dir work_dirs/MTL_swin-t-p4-w7_1x1_dior运行这个命令运行到这出现错误：
![image](https://github.com/user-attachments/assets/c79a2652-cc40-4d6d-ad54-ac84999ec9dc)
bao'cuo'w报错为：
![image](https://github.com/user-attachments/assets/775f79fe-1a5d-40cf-bb1c-d686f5142d5d)
是我数据集设置的原因还是什么原因，我的数据集dior路径为：
![image](https://github.com/user-attachments/assets/18d75810-66ca-4316-b345-1e928a51c775)
文件就是下载的你提供的json文件

**Comment by ClearMind999** [comment]
我也遇到了这个错误

**Comment by Li-Qingyun** [comment]
这一段应该是可以ignore的，因为这块就是print一个demo用来check

**Comment by Li-Qingyun** [comment]
https://github.com/Li-Qingyun/RSCoTr/blob/11044ee3bfe966aea5272400f668fb935acf039a/mtl/data/build.py#L82-L88

就是这几行，注释其实也没什么吧

**Comment by ClearMind999** [comment]
> 这一段应该是可以ignore的，因为这块就是print一个demo用来check

谢谢，注释掉，已经跑起来了

**Comment by Li-Qingyun** [comment]
你们的iter_list是不是少啊，看起来是不是不是三个任务？

**Comment by Li-Qingyun** [comment]
这里写死了，是看三个任务
get_iter_list 是我让iteration strategy吐出来一个序列试试看是啥呀的用来check
get_p_list 是看不同任务的迭代次数比例

这里都是只看 (0, 1, 2) 的

**Comment by ClearMind999** [comment]
> 你们的iter_list是不是少啊，看起来是不是不是三个任务？

是的，我用自己数据集跑的两个任务

**Comment by zjh299** [comment]
![image](https://github.com/user-attachments/assets/d0e510ad-52fb-4354-9535-e0fdf93e84f9)
按照你的方式改了后还是不可以啊

**Comment by Li-Qingyun** [comment]
self.dataloaders --> data_loaders
