### ISSUE TITLE
源码安装与包管理器安装

### ISSUE THREAD

**Issue by ClearMind999** [Li-Qingyun/RSCoTr#12]
作者你好，你的代码是使用pip安装，而非源码安装。所以我在修改模型，比如将swintransformer修改为其他模型时，会报错‘XX’ is not int the models registry 。如果是源码安装的话，通过python setup.py install可以解决。所以有几个问题烦请解答。
1.使用pip安装，如何解决这个问题？
2.我看到了models/seg/rscotr_seg.py 这些也会出现这个问题，请问你是如何解决的？
3.如果要替换一个新的backbone应该要修改那几个文件？
希望您能解答，谢谢

**Comment by Li-Qingyun** [comment]
注册器找不到模块，mmcv的经典难题了，死去的记忆开始攻击我
讲真太久远了，乍一下我也想不起来该怎么确保注册器能拿到增加的模型。真的好久没用mmcv了

但是我想到您这里有一个可能性和上面说的没关系，
比如，您说从源码安装，但是指定版本的非开发者模式很少从源码安装，您是否使用了类似 `git checkout v2.25.1` 这样的操作？不然您安装的mmdet似乎可能是新版的，您也可以用 `pip show mmdet` 来检查下版本。

建议您检查下是不是我说的这个情况，如果仍有问题建议多提一点细节

**Comment by ClearMind999** [comment]
没有使用过类似 git checkout v2.25.1 这样的操作

我采用的是，readme中的mim安装方式。源码安装应该是通过git clone mmsegmentation安装。后者可以在mmseg目录中添加自己的模型，然后通过python setup.py install 加入registry。

你这个通过mim安装的，我不太清楚该如何添加新模型以及将新模型加入registry。

或者根据configs/seg/RSCoTrSeg_3scale_swin-t.....，执行model/seg/rscotr_seg.py 也会出现注册器找不到模块的问题，您当时是怎么解决的

**Comment by Li-Qingyun** [comment]
> 没有使用过类似 git checkout v2.25.1 这样的操作

说明你安装的是新版啊
