### ISSUE TITLE
默认训练策略是什么

### ISSUE THREAD

**Issue by Whu-rs-lcx** [Li-Qingyun/RSCoTr#13]
您好，我想问一下直接使用MTL_slvlcls_swin-t-p4-w7_1x1_resisc&dior&potsdam.py文件是采用的什么训练策略？是single-task baseline 吗？

**Comment by Li-Qingyun** [comment]
@Whu-rs-lcx nonono，这个就是multi task了，训练策略默认是 round robin

**Comment by megumin1117** [comment]
您好，请问“ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [28, 28] and output size of torch.Size([224, 224, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.”这个错误有遇到怎末解决吗

**Comment by Li-Qingyun** [comment]
你说的对的，30000这个其实是没有意义的，不过这个变量在后面用的时候，分母会被抵消掉，所以是没影响的

这里前两天修了个bug，可以更新下
