### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by megumin1117** [Li-Qingyun/RSCoTr#14]
您好，请问“ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [28, 28] and output size of torch.Size([224, 224, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.”这个错误有遇到怎末解决吗

**Comment by Li-Qingyun** [comment]
信息太少，不太清楚，显然是输入有问题

**Comment by megumin1117** [comment]
> 信息太少，不太清楚，显然是输入有问题
您好这是完整报错，您意思是数据集的问题吗
<img width="1826" alt="1733833308422" src="https://github.com/user-attachments/assets/fe3d0520-8b3c-43da-b6d7-e4f88653008d">

**Comment by Li-Qingyun** [comment]
这看起来不像是我们的数据啊，看起来是灰度图

**Comment by megumin1117** [comment]
> 这看起来不像是我们的数据啊，看起来是灰度图

单独跑dior数据集没有问题，跑potsdam时报这个错误，我看都是公开数据集所以是和您这边数据格式不一致的原因是吗

**Comment by Li-Qingyun** [comment]
是公开数据集的，但是这个报错看起来像是单纬度的图，是不是gt和input反了哇

**Comment by megumin1117** [comment]
> 是公开数据集的，但是这个报错看起来像是单维度的图，是不是gt和input反了哇

emmmm应该是没有反的

**Comment by Li-Qingyun** [comment]
@megumin1117 log里面会有完整的config，或者你把log粘贴上来呗？

**Comment by megumin1117** [comment]
> @megumin1117 log里面会有完整的config，或者你把log粘贴上来呗？
我修改过“mtl/data/build.py”这个路径文件中85行，由于训练开始时除数一直为零将min改为max
请问您会是这里影响的吗
[20241213_174850.log](https://github.com/user-attachments/files/18124366/20241213_174850.log)
<img width="465" alt="1734083570362" src="https://github.com/user-attachments/assets/d4a3adf6-8d4a-43d9-85f6-348358794e57" />

**Comment by Li-Qingyun** [comment]
这个地方之前确实有bug，你可能需要更新一下代码，或者干脆注释掉这部分，这个函数主要用来print

**Comment by Li-Qingyun** [comment]
哦哦，这个log看起来没啥毛病，感觉还是数据的问题

**Comment by ClearMind999** [comment]
@Li-Qingyun 你好，你这个代码训练出来权重后，如何进行分类精度的评估？我使用test.py会生成img/存放分割结果，还有一个json文件存放分割各种指标。但是没有有关分类精度的文件，比如这个权重的对应每个类别的分类精度？我看到mmClassification里面倒是有画混淆矩阵，pr曲线，roc曲线的工具，但是不知道你这个代码是如何获取分类精度的？希望解答，谢谢

**Comment by Li-Qingyun** [comment]
> @Li-Qingyun 你好，你这个代码训练出来权重后，如何进行分类精度的评估？

训练的时候log里面就有啊，test也有啊，有个resisc/acc类似这样的

**Comment by ClearMind999** [comment]
确实有，不过那个应该是验证集的精度，我想评估测试集的精度



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月18日(星期三) 上午10:13
收件人: "Li-Qingyun/RSCoTr";
抄送: "Comment";
主题: Re: [Li-Qingyun/RSCoTr] 训练问题 (Issue #14)





  
@Li-Qingyun 你好，你这个代码训练出来权重后，如何进行分类精度的评估？
  
训练的时候log里面就有啊，test也有啊，有个resisc/acc类似这样的
 
&mdash;

**Comment by Li-Qingyun** [comment]
https://github.com/Li-Qingyun/RSCoTr/blob/bf21c5cd528bb0b242855c33f3588f37c9c2875d/configs/_base_/cls/resisc_swin_224.py#L60

这行改成test呗，我印象里我本地就是test 
`ln -s val test` 应该是用了软链接

https://github.com/Li-Qingyun/RSCoTr/blob/master/tools/test_without_det_eval.py
https://github.com/Li-Qingyun/RSCoTr/blob/master/tools/test.py

另外，这俩文件就是跑test的点数啊

**Comment by Li-Qingyun** [comment]
没有啊，是多任务的啊

**Comment by Li-Qingyun** [comment]
会不会是这样，分类不是一个大表来的，你在控制台输出搜索一下 resisc 这个字段

**Comment by ClearMind999** [comment]
是这样的，之前把--show删掉了，但是这个精度是总的精度，而没有每个类别的精度，单类别的该如何获取？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Li-Qingyun/RSCoTr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Li-Qingyun/RSCoTr] 训练问题 (Issue #14)





 
会不会是这样，分类不是一个大表来的，你在控制台输出搜索一下 resisc 这个字段

**Comment by Li-Qingyun** [comment]
555，没写单类别精度的功能，我论文里只标了总的

**Comment by megumin1117** [comment]
您方便说一下您这边potsdam数据集中label的数据格式吗

**Comment by Li-Qingyun** [comment]
我follow了wangdi师兄的RSP的格式

看起来很麻烦的话，我可以去找一下当时处理好的数据和脚本，放在数据仓库里

我最近赶一下igarss2025，ddl是十一号，结束后可以邮件或者issue催一下我

**Comment by megumin1117** [comment]
> 我follow了wangdi师兄的RSP的格式
> 
> 看起来很麻烦的话，我可以去找一下当时处理好的数据和脚本，放在数据仓库里
> 
> 我最近赶了一下igarss2025，ddl是十一号，结束后可以邮件或者issue催一下我

解决了谢谢

**Comment by qing650** [comment]
> 我follow了wangdi师兄的RSP的格式
> 
> 看起来很麻烦的话，我可以去找一下当时处理好的数据和脚本，放在数据仓库里
> 
> 我最近赶一下igarss2025，ddl是十一号，结束后可以邮件或者issue催一下我

**Comment by qing650** [comment]
> 我follow了wangdi师兄的RSP的格式
> 
> 看起来很麻烦的话，我可以去找一下当时处理好的数据和脚本，放在数据仓库里
> 
> 我最近赶一下igarss2025，ddl是十一号，结束后可以邮件或者issue催一下我

你好，这个potsdam数据集你在哪上传了吗，
