### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by December2018** [Li-Qingyun/RSCoTr#2]
请问有多个针对单类的数据集，能够将其整合训练一个多分类的模型吗

**Comment by Li-Qingyun** [comment]
其实这种就用不上多任务框架了，直接一个多分类器模型就能解决，把loss从softmax给改成sigmoid。
但是要注意是不是有可能有语义混淆的问题，或者类别合并的问题，比如一个专门识别船的数据集和一个专门识别小型渔船的数据集，是需要考虑类别模糊的问题的
