### ISSUE TITLE
训练时出现的问题

### ISSUE THREAD

**Issue by HarmonRS** [Li-Qingyun/RSCoTr#4]
我在Windows系统上部署了该项目，已创建虚拟环境并安装了OpenMMLab所需的依赖项。在data文件夹中配置了DIOR、NWPU-RESISC45、Potsdam这三个数据集，其中DIOR数据集已转换为COCO格式，但在运行训练脚本时遇到了num_samples=0的错误，并未读到数据。我仔细检查了数据集的配置和路径设置，但未能找到问题的根源。

**Comment by Li-Qingyun** [comment]
我回忆了下，可能是类别不对齐，因为mmdet会根据类别过滤数据。
你可以看下[config里的类别](https://github.com/Li-Qingyun/RSCoTr/blob/11044ee3bfe966aea5272400f668fb935acf039a/configs/_base_/det/dior.py#L4-L8)，这里的类别应该和json里面的 categories 字段里面的字符串对应下，所以你要么处理下你的json，要么修正这个config的类别
我明天去看下dior的json文件，在一个之前的服务器里，应该就是类别字符串不完全一样造成的，我找到我就上传上去。

**Comment by Li-Qingyun** [comment]
[DIOR_train_coco.json](https://github.com/user-attachments/files/17742802/DIOR_train_coco.json)
[DIOR_test_coco.json](https://github.com/user-attachments/files/17742799/DIOR_test_coco.json)
[DIOR_val_coco.json](https://github.com/user-attachments/files/17742804/DIOR_val_coco.json)

**Comment by Li-Qingyun** [comment]
@HarmonRS
