### ISSUE TITLE
关于训练策略的疑惑

### ISSUE THREAD

**Issue by Whu-rs-lcx** [Li-Qingyun/RSCoTr#5]
您好，想请问您论文中的不同训练策略在项目里是怎么实现的，例如不同任务的训练顺序和批次等

**Comment by Li-Qingyun** [comment]
使用 IterationStrategy 对象对训练策略进行管理，其实现在 [mtl/data/iteration_strategies.py](https://github.com/Li-Qingyun/RSCoTr/blob/master/mtl/data/iteration_strategies.py)
IterationStrategy 是一个迭代器对象，会接收多个数据集的 dataloader 对象（这样你就可以定义它们各自的preprocessing pipeline和batch size等等），在每次迭代会返回按照策略选出的对应的数据集的 dataloader 对象

我们的数据集加载器类 MultiDataloader 能使用 IterationStrategy 管理多个 dataloader，其实现在 [mtl/data/multi_data_loader.py](https://github.com/Li-Qingyun/RSCoTr/blob/master/mtl/data/multi_data_loader.py)

这里可能会有一些 confusing 的地方，我印象里当初写的时候思考的问题，我罗列一些流水账上来，希望能帮到理解

mmcv 规定的训练器(runner)有两种
- epoch-based runner: 大循环 epoch，小循环 steps，每次要保证一个 epoch 内所有数据都迭代到
- iteration-based runner: 只有steps这个循环，会导致不同数据集的epoch index状态不对齐，例如一个100steps数据集a和200steps数据集b做round robin迭代，a跑两个epoch对应b跑一个

我选择的是 iteration-based runner，不推荐 epoch-based runner，原因如下
- 如果用 epoch-based runner，那我就需要想方设法地规定在一个 epoch 里把每个数据集的数据跑完跑干净，无论从工程实现还是训练的灵活性讲都是不合适的
- 我们并不限制各个数据集的batch size，加上数据集的尺度不一样，造成的结果是每个数据集的 data batch 个数基本铁定是不同的。如果用 epoch-based 的话
- 我们还是有相关的 random 的迭代策略的实现的，如果在一个epoch中某个数据集的所有样本都完成训练，按照epoch-based要求，就不能使用该数据集，直到其他数据集也被采样完成，这时randomness的特性就被破话了

在论文对这里也有一些说明，所以用 iteration-based 的方式做多任务学习是最灵活方便的，即无所吊谓每个样本被训练几次几个epoch这种事，把每个数据集都变成循环加载的模式，然后在每个加载器上加上 IterationStrategy 对象，你可以理解成一个单刀多制开关

从[这里](https://github.com/Li-Qingyun/RSCoTr/blob/11044ee3bfe966aea5272400f668fb935acf039a/mtl/data/multi_data_loader.py#L121-L175)可以看到利用IterationStrategy加载数据的逻辑

self.change_dataloader() 被调用意味着从 IterationStrategy 对象中获取下一个 batch 需要的新的 dataloader，[这部分](https://github.com/Li-Qingyun/RSCoTr/blob/11044ee3bfe966aea5272400f668fb935acf039a/mtl/data/multi_data_loader.py#L155-L166)遇到了当前数据集的 StopIteration，意味着这个数据集已经迭代完一次，进入这个数据集的下一个epoch了，此时会刷新它的迭代器

你会发现这样设计后，数据加载反而灵活了很多。不需要管不同数据集之间的对齐问题（例如对齐预处理，对齐batch数量等等），而且可以随意调控每次迭代要用哪个数据集。

如果显存足够的话，当然也推荐梯度累计的方式，在一次梯度更新过程里把每个任务都训练了。不进行梯度累计对显存非常友好，我当时可以在一张3070上完成这个实验的。

**Comment by Whu-rs-lcx** [comment]
感谢分享，大致明白了！

**Comment by zjh299** [comment]
请问一下改变训练策略要在哪里改变呢，我看代码配置里面只有两个strategy）
![屏幕截图 2024-11-18 101403](https://github.com/user-attachments/assets/a9a82da0-3098-4419-9be0-96ce65d9a7a0)

**Comment by Li-Qingyun** [comment]
[configs/multi/slvl_strategies](https://github.com/Li-Qingyun/RSCoTr/tree/master/configs/multi/slvl_strategies) 都在这个文件夹里

**Comment by Li-Qingyun** [comment]
> 请问一下改变训练策略要在哪里改变呢，我看代码配置里面只有两个strategy）
@zjh299 
[configs/multi/slvl_strategies](https://github.com/Li-Qingyun/RSCoTr/tree/master/configs/multi/slvl_strategies) 都在这个文件夹里

**Comment by zjh299** [comment]
在哪里使用的这个文件夹呢

**Comment by Li-Qingyun** [comment]
😥 这个文件夹就是config啊，用这个可以直接跑起来

**Comment by zjh299** [comment]
我知道这个，我的意思是在代码里面运行的是MTL_swin-t-p4-w7_1x1_resisc&dior&potsdam.py这个配置文件，命令是python tools/train.py configs/multi/MTL_slvlcls_swin-t-p4-w7_1x1_resisc&dior&potsdam.py --load-task-pretrain --work-dir work_dirs/MTL_slvlcls_swin-t-p4-w7_1x1_resisc&dior&potsdam，那么他是怎么指定用的某种策略呢，并没有用[configs/multi/slvl_strategies](https://github.com/Li-Qingyun/RSCoTr/tree/master/configs/multi/slvl_strategies)配置文件

![image](https://github.com/user-attachments/assets/9a0d0900-e4c5-49da-af1b-7606f6bacd2a)

**Comment by zjh299** [comment]
我好像明白了，太局限了是不是运行那个配置文件就可以啊，把configs/multi/MTL_slvlcls_swin-t-p4-w7_1x1_resisc&dior&potsdam.py替换为configs\multi\slvl_strategies\repeated_sequence.py就可以啊

**Comment by Li-Qingyun** [comment]
是这个意思

**Comment by zjh299** [comment]
可以大概描述下这些配置文件分别是做什么实验的吗
![image](https://github.com/user-attachments/assets/50eac204-0a05-40c3-b617-95f33c8f5090)

**Comment by Li-Qingyun** [comment]
> 可以大概描述下这些配置文件分别是做什么实验的吗

> model文件夹下这3个文件夹是分别3个模型吗还是什么，他们是用来做什么的

这些部分是开发阶段的一些单任务的模块，也可以理解为 RSCoTr 的单任务，理论上是等效于mtl的在单数据集上训练的

可以不必理会

**Comment by zjh299** [comment]
所以说只需关注model和config下的multi即可是吗

**Comment by Li-Qingyun** [comment]
可以
