### ISSUE TITLE
Training Time Issue

### ISSUE THREAD

**Issue by moonboy12138** [Li-Qingyun/RSCoTr#7]
Great Work! I successfully ran the code using completely default settings, but it seems like the training time is quite unusual. The training takes an extremely long time. For example, I trained on three demo datasets: 600 images from the RESISC45 dataset, 12 images from the DIOR dataset, and 12 images from the PotsDam dataset. Training for 300,000 iterations took 40 hours! Could you advise on what adjustments are needed to achieve a normal training speed?  

I'm using an RTX 3090. Could you also let me know how long the training time is on a TESLA V100? Thank you!

**Comment by Li-Qingyun** [comment]
within 30 hours, i forgot. but not too long.

**Comment by Li-Qingyun** [comment]
this is just the running config of normal speed. 300k iterations 40h seems normal

**Comment by Li-Qingyun** [comment]
Wait a moment. I'm busy on rebuttal. I'll share a log and more details.

**Comment by Li-Qingyun** [comment]
[20221013_104659.log](https://github.com/user-attachments/files/17799526/20221013_104659.log)
I've anonymised some of the privacy concerns in this log.

It seems that the open-sourced checkpoint was resumed from a intermediate checkpoint from an interrupt experiment.
The 100k resuming steps takes about 10 hours (2022-10-13 10:47 -> 2022-10-13 20:36).

Your 300k steps may take 30 hours on my device.

**Comment by Li-Qingyun** [comment]
> Actually I only used the very small subset of three datasets (like I said in the first question), not all the data, therefore it looks like abnormal

The sample number makes no sense for training time. Actually, the training steps does, doesn't it?
