### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zjh299** [Li-Qingyun/RSCoTr#8]
![image](https://github.com/user-attachments/assets/875b56c7-12d4-4ae0-8537-2ebcf93e1105)
运行python tools/train.py configs/multi/MTL_slvlcls_swin-t-p4-w7_1x1_resisc&dior&potsdam.py --load-task-pretrain --work-dir work_dirs/MTL_slvlcls_swin-t-p4-w7_1x1_resisc&dior&potsdam时出现此错误，但是mtl.apis不是在文件夹下吗

**Comment by Li-Qingyun** [comment]
命令前面加上 PYTHONPATH=".:$PYTHONPATH" 的环境变量

**Comment by zjh299** [comment]
![image](https://github.com/user-attachments/assets/8f54caea-1d77-42b7-85b8-ba38d005de96)
还是报错

**Comment by zjh299** [comment]
![image](https://github.com/user-attachments/assets/b4144cd5-fbf1-4125-882f-5e958ce22370)

**Comment by Li-Qingyun** [comment]
应该是 /root/RSCoTr

**Comment by zjh299** [comment]
![image](https://github.com/user-attachments/assets/6ae09e3c-9137-4ff7-ba5d-f1d053022994)
z怎么出了更多啊

**Comment by zjh299** [comment]
![image](https://github.com/user-attachments/assets/da899f2b-a21d-4e62-bd1c-bedf35d8846b)

**Comment by zjh299** [comment]
我看一下稍等

**Comment by zjh299** [comment]
数据集data路径下都怎么放可以给个截图吗
